version: 2

jobs:
  test-py27:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: python setup.py pytest
  test-py35:
    docker:
      - image: circleci/python:3.5-jessie-node
    steps:
      - checkout
      - run: python setup.py pytest
  deploy-to-pypi:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = randy3k" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run: |
          python setup.py sdist
          sudo pip install twine
          twine upload dist/*


workflows:
  version: 2
  test:
    jobs:
      - test-py27
      - test-py35
  deploy:
    jobs:
      - test-py27:
          filters:
            tags:
              only: /^v.*/
      - test-py35:
          filters:
            tags:
              only: /^v.*/
      - deploy-to-pypi:
          requires:
            - test-py27
            - test-py35
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
